checkpoint: bris-fiab-malawi.ckpt 

date: "2025-03-06"

lead_time: 0

input:
  cutout:
    lam_0:
      downscaled_mars:
        log: false
        grid: "0.1/0.1"
        area: "-8/30/-22/43"
        cache_dir: .cache
        pre_processors:
          - apply_adiabatic_corrections
    global:
      cached_mars:
        cache_dir: .cache
        log: false
      mask: 'global/cutout_mask'

output:
  tee:
    outputs:
      - printer
      - extract_lam:
          output:
            netcdf: out.nc
