checkpoint: malawi_20250929.ckpt

date: "2025-03-06"

lead_time: 0

input:
  cutout:
    lam_0:
      downscaled_mars:
        log: true
        grid: "0.1/0.1"
        area: "-8/30/-22/43"
        # pre_processors:
        #   - apply_adiabatic_corrections
    global:
      mars:
        log: true
      mask: 'global/cutout_mask'

output:
  tee:
    outputs:
      - printer
      - extract_lam:
          output:
            netcdf: out.nc
