checkpoint: checkpoint.ckpt

date: "2025-03-05"

#lead_time: 72

input:
  cutout:
    lam_0:
      mars:
        log: false
        grid: "0.025/0.025"
        area: "-8/30/-22/43"
    global:
      mars:
        log: false
      mask: 'global/cutout_mask'

output:
  tee:
    outputs:
      - printer
      - extract_lam:
          output:
            netcdf: out.nc
