checkpoint: malawi_normalized_0_025.ckpt

date: "2025-04-06"

lead_time: 0

input:
  cutout:
    lam_0:
      mars:
        log: true
        grid: "0.025/0.025"
        area: "-8/30/-22/43"
        pre_processors:
          - apply_adiabatic_corrections
    global:
      mars:
        log: false
      mask: 'global/cutout_mask'

output:
  tee:
    outputs:
      - printer
      - extract_lam:
          output:
            netcdf: out.nc
